[tool.poetry]
name = "clinic"
version = "0.1.0"
description = ""
authors = [
    "AsuraBot <homecat13@gmail.com>",
    "GurgenXD <gurgen.abramyan.1995@gmail.com>"
]
readme = "README.md"
packages = [
    {include = "clinic"}
]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.89.1"
uvicorn = {extras = ["standard"], version = "0.20.0"}
click = "8.1.3"
SQLAlchemy = "2.0.0"
alembic = "1.9.2"
pydantic = {extras = ["dotenv"], version = "1.10.4"}
asyncpg = "0.27.0"
sqladmin = "0.9.0"
dependency-injector = "4.41.0"
aiofiles = "22.1.0"

[tool.poetry.group.dev.dependencies]
black = "23.1.0"
mypy = "0.991"
pytest = "7.2.1"
pytest-cov = "4.0.0"
pytest-deadfixtures = "2.2.1"
ruff = "0.0.246"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py311"]
skip-magic-trailing-comma = true

[tool.ruff]
line-length = 100
target-version = "py311"
select = ["ALL"]
ignore = [
    "RUF001", "RUF002", "RUF003", "D104", "D100", "D107", "COM812", "ANN101", "D106",
    "A002", "A003", "FBT003", "D105", "TCH003", "TCH002", "D203", "D213"
]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]
"migrations/versions/*.py" = ["D103"]

[tool.ruff.isort]
lines-after-imports = 2
