[tool.poetry]
name = "clinic-async"
version = "0.1.0"
description = ""
authors = [
    "AsuraBot <homecat13@gmail.com>",
    "GurgenXD <gurgen.abramyan.1995@gmail.com>"
]
readme = "README.md"
packages = [
    {include = "clinic_async"}
]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "0.89.1"
uvicorn = {extras = ["standard"], version = "0.20.0"}
click = "8.1.3"
SQLAlchemy = "2.0.0"
alembic = "1.9.2"
pydantic = {extras = ["dotenv"], version = "1.10.4"}
asyncpg = "0.27.0"
sqladmin = {git = "https://github.com/aminalaee/sqladmin.git", branch = "main"}
dependency-injector = "4.41.0"
aiofiles = "22.1.0"

[tool.poetry.group.dev.dependencies]
black = "23.1.0"
mypy = "0.991"
pylint = "2.15.10"
isort = "5.11.4"
pytest = "7.2.1"
pytest-cov = "^4.0.0"
pytest-deadfixtures = "^2.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
target-version = ["py311"]
skip-magic-trailing-comma = true

[tool.isort]
profile = "black"
line_length = 100