"""Modified page model.

Revision ID: a253537e2498
Revises: 3b383c106c61
Create Date: 2022-10-18 13:05:47.653953

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "a253537e2498"
down_revision = "3b383c106c61"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pages", sa.Column("slug", sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, "pages", ["slug"])
    op.drop_column("pages", "url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pages", sa.Column("url", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "pages", type_="unique")
    op.drop_column("pages", "slug")
    # ### end Alembic commands ###
