"""offices

Revision ID: 4a7cdbf0969f
Revises: a253537e2498
Create Date: 2022-12-25 13:51:10.817375

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4a7cdbf0969f"
down_revision = "a253537e2498"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "offices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=True),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=False),
        sa.Column("work_time", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=30), nullable=False),
        sa.Column("map_code", sa.String(length=500), nullable=True),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("contacts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("city", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("address", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("work_time", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column("phone", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        sa.Column("map_code", sa.VARCHAR(length=500), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name="contacts_pkey"),
    )
    op.drop_table("offices")
    op.drop_table("cities")
    # ### end Alembic commands ###
