"""init.

Revision ID: 74b3c392d767
Revises: 
Create Date: 2022-10-17 12:56:25.743822

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "74b3c392d767"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyzes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("preparation", sa.Text(), nullable=True),
        sa.Column("period", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analyzes_types",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "callbacks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("answered", sa.Boolean(), nullable=True),
        sa.Column("call_back_time", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contacts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("city", sa.String(length=30), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=False),
        sa.Column("work_time", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=30), nullable=False),
        sa.Column("map_code", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "news",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("preview", sa.String(length=50), nullable=False),
        sa.Column("created", sa.DateTime(), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("photo", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "promotions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("sale", sa.String(length=30), nullable=False),
        sa.Column("title", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("photo", sa.String(length=150), nullable=True),
        sa.Column("services", sa.String(length=100), nullable=False),
        sa.Column("date_start", sa.DateTime(), nullable=False),
        sa.Column("date_end", sa.DateTime(), nullable=False),
        sa.Column("url", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("on_main", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "services_types",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("on_main", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specialists",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("photo", sa.String(length=150), nullable=True),
        sa.Column("start_work_date", sa.Date(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("on_main", sa.Boolean(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specializations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=True),
        sa.Column("email", sa.String(length=64), nullable=True),
        sa.Column("password", sa.String(length=32), nullable=False),
        sa.Column("created", sa.Date(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "analyzes_types_analyzes",
        sa.Column("analysis_type_id", sa.BigInteger(), nullable=False),
        sa.Column("analysis_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyzes.id"]),
        sa.ForeignKeyConstraint(["analysis_type_id"], ["analyzes_types.id"]),
        sa.PrimaryKeyConstraint("analysis_type_id", "analysis_id"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("service_type_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("on_main", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(["service_type_id"], ["services_types.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specializations_specialists",
        sa.Column("specialization_id", sa.BigInteger(), nullable=False),
        sa.Column("specialist_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["specialist_id"], ["specialists.id"]),
        sa.ForeignKeyConstraint(["specialization_id"], ["specializations.id"]),
        sa.PrimaryKeyConstraint("specialization_id", "specialist_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("specializations_specialists")
    op.drop_table("services")
    op.drop_table("analyzes_types_analyzes")
    op.drop_table("users")
    op.drop_table("specializations")
    op.drop_table("specialists")
    op.drop_table("services_types")
    op.drop_table("promotions")
    op.drop_table("pages")
    op.drop_table("news")
    op.drop_table("contacts")
    op.drop_table("callbacks")
    op.drop_table("analyzes_types")
    op.drop_table("analyzes")
    # ### end Alembic commands ###
