"""specialsts online.

Revision ID: aa11cc4ab6e7
Revises: 5cc888a799dc
Create Date: 2023-02-04 17:29:30.120183

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "aa11cc4ab6e7"
down_revision = "5cc888a799dc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("specialists", sa.Column("can_online", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specialists", "can_online")
    # ### end Alembic commands ###
