"""Migration message.

Revision ID: ea5bbe9400e5
Revises: af9d19e859b3
Create Date: 2023-02-18 11:51:11.195037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ea5bbe9400e5"
down_revision = "af9d19e859b3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "updates", "error_log", existing_type=sa.String(500), type_=sa.TEXT(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "updates", "error_log", existing_type=sa.TEXT(), type_=sa.String(500), nullable=True
    )
    # ### end Alembic commands ###
