"""Short description size.

Revision ID: b418025ad13e
Revises: 65d98c13d263
Create Date: 2023-12-23 10:51:05.699383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b418025ad13e"
down_revision = "65d98c13d263"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "services", "short_description", existing_type=sa.VARCHAR(length=255), type_=sa.Text(), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "services", "short_description", existing_type=sa.Text(), type_=sa.VARCHAR(length=255), existing_nullable=True
    )
    # ### end Alembic commands ###
