"""work with news

Revision ID: a5e06e2725cd
Revises: 44ec22f02284
Create Date: 2023-02-16 10:40:39.958534

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a5e06e2725cd"
down_revision = "44ec22f02284"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "photo",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.VARCHAR(length=150),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "photo",
        existing_type=sa.VARCHAR(length=150),
        type_=sa.VARCHAR(length=50),
        nullable=False,
    )
    # ### end Alembic commands ###
