"""specialsts certificates.

Revision ID: 5cc888a799dc
Revises: f485efa94761
Create Date: 2023-02-04 15:52:56.373300

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "5cc888a799dc"
down_revision = "f485efa94761"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialist_certificates",
        sa.Column("specialist_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("path", sa.String(length=150), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["specialist_id"], ["specialists.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("specialists", sa.Column("education", sa.Text(), nullable=False))
    op.add_column("specialists", sa.Column("activity", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specialists", "activity")
    op.drop_column("specialists", "education")
    op.drop_table("specialist_certificates")
    # ### end Alembic commands ###
