"""work with 1c specialist

Revision ID: 965e2658f216
Revises: f1ef76913394
Create Date: 2023-02-16 15:06:47.883965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "965e2658f216"
down_revision = "f1ef76913394"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "specializations_specialists_specialist_id_fkey",
        "specializations_specialists",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "specializations_specialists",
        "specialists",
        ["specialist_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "specializations_specialists", type_="foreignkey")
    op.create_foreign_key(
        "specializations_specialists_specialist_id_fkey",
        "specializations_specialists",
        "specialists",
        ["specialist_id"],
        ["id"],
    )
    # ### end Alembic commands ###
