"""Added Consultation.

Revision ID: 65d98c13d263
Revises: 15165703b82e
Create Date: 2023-12-02 16:14:40.493496

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "65d98c13d263"
down_revision = "15165703b82e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "consultations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("specialist", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("comments", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("consultations")
    # ### end Alembic commands ###
