"""work with 1c specialist

Revision ID: b92ed5bd24bb
Revises: 1a9e81503d02
Create Date: 2023-02-16 15:16:21.116486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b92ed5bd24bb"
down_revision = "1a9e81503d02"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("specialists", sa.Column("guid_1c", sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specialists", "guid_1c")
    # ### end Alembic commands ###
