"""spec_titules.

Revision ID: c897cf1f6b25
Revises: 0fb73dc4a411
Create Date: 2023-01-14 14:27:20.115839

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c897cf1f6b25"
down_revision = "0fb73dc4a411"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("specialists", sa.Column("titules", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specialists", "titules")
    # ### end Alembic commands ###
