"""work with promotions.

Revision ID: 46a184094ef4
Revises: 9afd68c7b708
Create Date: 2023-02-16 12:00:19.851376

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "46a184094ef4"
down_revision = "9afd68c7b708"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("date_start", sa.Date(), nullable=False))
    op.add_column("promotions", sa.Column("date_end", sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("promotions", "date_end")
    op.drop_column("promotions", "date_start")
    # ### end Alembic commands ###
