"""Initial commit.

Revision ID: d4e5bcf41a8b
Revises:
Create Date: 2023-09-17 15:19:35.754522

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "d4e5bcf41a8b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analyzes",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("preparation", sa.Text(), nullable=True),
        sa.Column("period", sa.String(length=30), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analyzes_types",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "callbacks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("answered", sa.Boolean(), nullable=False),
        sa.Column("call_back_time", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "licenses",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("document", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "news",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=50), nullable=False),
        sa.Column("preview", sa.String(length=150), nullable=False),
        sa.Column("created", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=False),
        sa.Column("photo", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "pages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("title", sa.String(length=20), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "promotions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("sale", sa.String(length=30), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("photo", sa.String(length=150), nullable=False),
        sa.Column("date_start", sa.Date(), nullable=False),
        sa.Column("date_end", sa.Date(), nullable=False),
        sa.Column("on_main", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "services",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("short_description", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_group", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("on_main", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["parent_id"], ["services.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "services_types",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.Column("on_main", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specialists",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("surname", sa.String(length=50), nullable=False),
        sa.Column("patronymic", sa.String(length=50), nullable=True),
        sa.Column("photo", sa.String(length=150), nullable=True),
        sa.Column("start_work_date", sa.Date(), nullable=False),
        sa.Column("education", sa.Text(), nullable=False),
        sa.Column("activity", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("titles", sa.Text(), nullable=True),
        sa.Column("can_adult", sa.Boolean(), nullable=False),
        sa.Column("can_child", sa.Boolean(), nullable=False),
        sa.Column("can_online", sa.Boolean(), nullable=False),
        sa.Column("on_main", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specializations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=30), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "updates",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("start_update", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_update", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_log", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "analyzes_types_analyzes",
        sa.Column("analysis_type_id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyzes.id"]),
        sa.ForeignKeyConstraint(["analysis_type_id"], ["analyzes_types.id"]),
        sa.PrimaryKeyConstraint("analysis_type_id", "analysis_id"),
    )
    op.create_table(
        "offices",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=False),
        sa.Column("address", sa.String(length=100), nullable=False),
        sa.Column("work_time", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=False),
        sa.Column("email", sa.String(length=30), nullable=False),
        sa.Column("main_doctor", sa.String(length=50), nullable=False),
        sa.Column("main_doctor_work_time", sa.String(length=50), nullable=False),
        sa.Column("coor_x", sa.String(length=10), nullable=False),
        sa.Column("coor_y", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(["city_id"], ["cities.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specialist_certificates",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("specialist_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=250), nullable=False),
        sa.Column("path", sa.String(length=150), nullable=False),
        sa.ForeignKeyConstraint(["specialist_id"], ["specialists.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "specializations_specialists",
        sa.Column("specialization_id", sa.String(length=36), nullable=False),
        sa.Column("specialist_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["specialist_id"], ["specialists.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["specialization_id"], ["specializations.id"]),
        sa.PrimaryKeyConstraint("specialization_id", "specialist_id"),
    )
    op.create_table(
        "departments",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("office_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("tags", sa.String(length=100), nullable=True),
        sa.Column("short_description", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("photo", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["office_id"], ["offices.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("departments")
    op.drop_table("specializations_specialists")
    op.drop_table("specialist_certificates")
    op.drop_table("offices")
    op.drop_table("analyzes_types_analyzes")
    op.drop_table("updates")
    op.drop_table("specializations")
    op.drop_table("specialists")
    op.drop_table("services_types")
    op.drop_table("services")
    op.drop_table("promotions")
    op.drop_table("pages")
    op.drop_table("news")
    op.drop_table("licenses")
    op.drop_table("cities")
    op.drop_table("callbacks")
    op.drop_table("analyzes_types")
    op.drop_table("analyzes")
    # ### end Alembic commands ###
