"""work with services.

Revision ID: 44ec22f02284
Revises: dc764bf5bb06
Create Date: 2023-02-09 15:00:31.291194

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "44ec22f02284"
down_revision = "dc764bf5bb06"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("services_types", sa.Column("is_active", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("services_types", "is_active")
    # ### end Alembic commands ###
