"""Refactor documents.

Revision ID: 15165703b82e
Revises: 2297a981bce1
Create Date: 2023-11-06 13:23:06.305138

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "15165703b82e"
down_revision = "2297a981bce1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "name", existing_type=sa.VARCHAR(length=50), type_=sa.String(length=255), existing_nullable=False
    )
    op.alter_column("documents", "link", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.drop_constraint("documents_guid_key", "documents", type_="unique")
    op.drop_column("documents", "guid")
    op.drop_column("documents", "file")
    op.add_column("documents_categories", sa.Column("name", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("documents_categories", "name")
    op.add_column("documents", sa.Column("file", sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column("documents", sa.Column("guid", sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_unique_constraint("documents_guid_key", "documents", ["guid"])
    op.alter_column("documents", "link", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.alter_column(
        "documents", "name", existing_type=sa.String(length=255), type_=sa.VARCHAR(length=50), existing_nullable=False
    )
    # ### end Alembic commands ###
