"""Consultation comments.

Revision ID: 82105c470f83
Revises: b418025ad13e
Create Date: 2023-12-23 11:01:09.681946

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "82105c470f83"
down_revision = "b418025ad13e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("consultations", "comments", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("consultations", "comments", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
