"""Initial commit.

Revision ID: 2297a981bce1
Revises: 474c05a45c22
Create Date: 2023-11-06 12:50:32.832194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2297a981bce1"
down_revision = "474c05a45c22"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("sale_period", sa.String(length=100), nullable=False))
    op.drop_constraint("promotions_guid_key", "promotions", type_="unique")
    op.drop_column("promotions", "guid")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("guid", sa.VARCHAR(length=36), autoincrement=False, nullable=False))
    op.create_unique_constraint("promotions_guid_key", "promotions", ["guid"])
    op.drop_column("promotions", "sale_period")
    # ### end Alembic commands ###
