"""Migration message.

Revision ID: af9d19e859b3
Revises: b92ed5bd24bb
Create Date: 2023-02-16 16:49:07.058284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af9d19e859b3"
down_revision = "b92ed5bd24bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "updates",
        sa.Column("start_update", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("end_update", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error_log", sa.String(length=500), nullable=True),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("updates")
    # ### end Alembic commands ###
