"""work with departments.

Revision ID: f1ef76913394
Revises: 977d2f7c0fd5
Create Date: 2023-02-16 14:31:33.601841

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f1ef76913394"
down_revision = "977d2f7c0fd5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "departments",
        sa.Column("office_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("tags", sa.String(length=100), nullable=True),
        sa.Column("short_description", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("photo", sa.String(length=150), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.ForeignKeyConstraint(["office_id"], ["offices.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_column("promotions", "is_active")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promotions", sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=False)
    )
    op.drop_table("departments")
    # ### end Alembic commands ###
