"""Initial commit.

Revision ID: 6e575ffe937f
Revises: 6f80eb4b2f97
Create Date: 2023-09-30 15:20:30.647300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e575ffe937f"
down_revision = "6f80eb4b2f97"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("catalogs", "page", existing_type=sa.VARCHAR(length=16), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("catalogs", "page", existing_type=sa.VARCHAR(length=16), nullable=False)
    # ### end Alembic commands ###
