"""spec_name.

Revision ID: 0fb73dc4a411
Revises: 3813bc49ebc7
Create Date: 2023-01-14 12:45:33.243023

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0fb73dc4a411"
down_revision = "3813bc49ebc7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("specialists", sa.Column("surname", sa.String(length=50), nullable=False))
    op.add_column("specialists", sa.Column("patronymic", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specialists", "patronymic")
    op.drop_column("specialists", "surname")
    # ### end Alembic commands ###
