"""work with 1c specialist

Revision ID: 1a9e81503d02
Revises: 965e2658f216
Create Date: 2023-02-16 15:10:52.493891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1a9e81503d02"
down_revision = "965e2658f216"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "specialist_certificates_specialist_id_fkey", "specialist_certificates", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "specialist_certificates",
        "specialists",
        ["specialist_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "specialist_certificates", type_="foreignkey")
    op.create_foreign_key(
        "specialist_certificates_specialist_id_fkey",
        "specialist_certificates",
        "specialists",
        ["specialist_id"],
        ["id"],
    )
    # ### end Alembic commands ###
