"""work with news

Revision ID: cd38cad7acb9
Revises: a5e06e2725cd
Create Date: 2023-02-16 10:42:04.686177

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd38cad7acb9"
down_revision = "a5e06e2725cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "preview",
        existing_type=sa.VARCHAR(length=50),
        type_=sa.VARCHAR(length=150),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "news",
        "preview",
        existing_type=sa.VARCHAR(length=150),
        type_=sa.VARCHAR(length=50),
        nullable=False,
    )
    # ### end Alembic commands ###
