"""work with promotions.

Revision ID: 9afd68c7b708
Revises: cd38cad7acb9
Create Date: 2023-02-16 11:32:39.298979

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "9afd68c7b708"
down_revision = "cd38cad7acb9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("promotions", sa.Column("name", sa.String(length=30), nullable=False))
    op.alter_column("promotions", "photo", existing_type=sa.VARCHAR(length=150), nullable=False)
    op.drop_column("promotions", "title")
    op.drop_column("promotions", "services")
    op.drop_column("promotions", "url")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "promotions", sa.Column("url", sa.VARCHAR(length=100), autoincrement=False, nullable=False)
    )
    op.add_column(
        "promotions",
        sa.Column("services", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    )
    op.add_column(
        "promotions", sa.Column("title", sa.VARCHAR(length=20), autoincrement=False, nullable=False)
    )
    op.alter_column("promotions", "photo", existing_type=sa.VARCHAR(length=150), nullable=True)
    op.drop_column("promotions", "name")
    # ### end Alembic commands ###
