"""Change callback model

Revision ID: 5ed7d16857f7
Revises: 11ef79646f2f
Create Date: 2024-04-20 12:03:03.719621

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5ed7d16857f7"
down_revision = "11ef79646f2f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("callbacks", "name")
    op.drop_column("callbacks", "call_back_time")
    op.drop_column("callbacks", "message")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("callbacks", sa.Column("message", sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column("callbacks", sa.Column("call_back_time", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column("callbacks", sa.Column("name", sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
