"""SEO description services and specialists.

Revision ID: 11ef79646f2f
Revises: 82105c470f83
Create Date: 2024-04-09 09:48:43.260381

"""

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "11ef79646f2f"
down_revision = "82105c470f83"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("services", sa.Column("seo_description", sa.Text(), nullable=True))
    op.add_column("specialists", sa.Column("seo_description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("specialists", "seo_description")
    op.drop_column("services", "seo_description")
    # ### end Alembic commands ###
