name: Tests-Linters

on: [push]

jobs:
  tests_linters:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Cache poetry install
      id: cache-poetry
      uses: actions/cache@v3
      with:
        path: ~/.local
        key: poetry-1.3.2

    - name: Install poetry
      if: steps.cache-poetry.outputs.cache-hit != 'true'
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Cache dependencies
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: .venv
        key: dependencies-${{ hashFiles('**/poetry.lock') }}

    - name: Install dependencies
      if: steps.cache-deps.outputs.cache-hit != 'true'
      run: poetry install --no-interaction --no-ansi --no-root

    # - name: Run tests
    #   run: make test

    - name: Run linters
      run: make lint
